server:
  port: 8085

spring:
  application:
    name: payment

  cloud:
    config:
      enabled:false

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root@39
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ZxvB6P1L9rQ8wH3nF4kT2mV7aJ5sD0gYabcdefgha